# Generated by Django 3.2.4 on 2021-06-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inicio_sesion',
            fields=[
                ('correo', models.IntegerField(primary_key=True, serialize=False, verbose_name='correo')),
                ('contraseña', models.CharField(max_length=20, verbose_name='contraseña')),
            ],
        ),
    ]
