# Generated by Django 3.2.4 on 2021-06-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Pais')),
                ('nombrePais', models.CharField(max_length=50, verbose_name='Nombre del Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Region')),
                ('nombreRegion', models.CharField(max_length=50, verbose_name='Nombre de la Region')),
            ],
        ),
    ]
