# Generated by Django 3.2.4 on 2021-06-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0002_pais_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colab',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('pais', models.CharField(max_length=20, verbose_name='Pais')),
                ('Region', models.CharField(max_length=20, verbose_name='Region')),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=60)),
                ('email', models.TextField(max_length=1000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
