# Generated by Django 3.2.4 on 2021-07-01 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0004_alter_colab_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colab',
            old_name='Region',
            new_name='region',
        ),
    ]
