# Generated by Django 3.2.4 on 2021-07-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0006_auto_20210630_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colab',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut'),
        ),
    ]
