# Generated by Django 3.2.4 on 2021-07-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0007_alter_colab_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inicio_sesion',
            name='contraseña',
        ),
        migrations.AlterField(
            model_name='colab',
            name='direccion',
            field=models.CharField(max_length=60, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='colab',
            name='email',
            field=models.CharField(max_length=60, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='colab',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='colab',
            name='pais',
            field=models.CharField(max_length=20, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='colab',
            name='region',
            field=models.CharField(max_length=20, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='colab',
            name='telefono',
            field=models.CharField(max_length=60, verbose_name='Telefono'),
        ),
    ]
